### ISSUE TITLE
Nice to have a requirements.txt

### ISSUE THREAD

**Issue by MohitB9** [marcoppasini/MelGAN-VC#10]
Good to have all requirements in place before triggering the notebook.
First thing is Nvidia GPU,
Just fyi, putting required packages that I had to install in a new virtual environment :
tensorflow-gpu
scipy
matplotlib
pillow
scikit-image
librosa
tqdm 
and 
torch

torch and torchaudio versions should be compatible with already existing CUDA version.

**Comment by marcoppasini** [comment]
Thank you for the help! I will add a requirements.txt as soon as I publish the next version of the system (I hope very soon!).

Thank you again for the help!
