### ISSUE TITLE
hop_length

### ISSUE THREAD

**Issue by CarolinGao** [marcoppasini/MelGAN-VC#11]
Hi, I encounter some problems when I try to change the  hop_length from 192 to 256. The results turns bad. I wonder that  is this some limitations of the model structure.
I want to change the hop_length because I want to use waveglow instead of griffin_lim and the waveglow request the hop_length to be 256.
Thanks, looking forward to your reply!

**Comment by marcoppasini** [comment]
Changing the hop parameter has consequences on both axis of the spectrogram: maybe try to also change the shape parameter (that controls the splitting on the x axis) to a lower value and see how the model performs!
