### ISSUE TITLE
Results: MelGAN-VC generated music

### ISSUE THREAD

**Issue by moiseshorta** [marcoppasini/MelGAN-VC#12]
Hello,

Thanks again for sharing this model, it's completely changed my electronic music production workflow in the past months.

I'd like to share some of the music I've been generating using exclusively MelGAN-VC:

[hexorcismos-transfiguracion](https://hexorcismos.bandcamp.com/album/-)
[MelGAN-VC generated electronic music mix](https://soundcloud.com/h-e-x-o-r-c-i-s-m-o-s/transfigurationclubmix-neural-3ball-mix)

Here is an article on the album which features more information on the creation process and a mention to this original repository:
[CreateDigitalMusic article](https://cdm.link/2020/07/transfiguracion-decolonizing-ai-in-hexorcismos-shamanistic-music-and-art/)

The training was done at 44.1Khz sample rate, with overall good but fuzzy results.
Further training of the models have proven to solve for a more coherent and good resolution sound.

If anybody is interested, I'd like to discuss possibilities of porting this model into a real time mode.

Cheers!

**Comment by marcoppasini** [comment]
Wow Moisés, that's incredible! Thanks for sharing!

I didn't really know how far my system could be pushed, and your generated music is completely out of my expectations.
Please if you know of some possible improvements that can be done to the system please let me know: I am sure that with your experience you may have some useful feedback.

Regarding achieving real-time inference with the model: the generation of the final spectrograms is actually incredibly fast (much faster that real time) but the slow part is inverting spectrograms back to waveform. The notebook now uses an iterative method (which takes some time to achieve good results) but there are some very fast ways to do the same thing involving neural networks, with maybe better results.
I hope to have time to look into that in the future, but if you're impatient you can try something yourself.

Huge congratulations again and thank you for your interest in MelGAN-VC!

**Comment by moiseshorta** [comment]
Hi Marco, I'm glad you enjoyed the music!

I've got a couple of comments and ideas to improve the model.

- Sample Rate and Transient preservation: 
I have successfully trained MelGAN-VC at a samplerate of 44.1kHz/16bits. Using these specific hyperparameters I achieved the results on the music you heard:

```
hop=512             
sr=44100             
min_level_db=-100     
ref_level_db=20

shape=64                       
vec_len=128           
bs = 16               
delta = 2.           
```

 Since the model is originally designed to work at 16Khz samplerate, I'm wondering if this is somehow hard-coded and if the audio information gets somehow compressed to this resolution when doing training, since it seems there is a lot of audio information loss, especially transients, get a bit lost when generating. Hope that makes sense.

Regarding the real time application, I haven't really tried it myself but I have seen some options to convert the spectrogram back to waveform in near real time. I will try and look into this as well.

All the best!

**Comment by materialvision** [comment]
Hi, I tried to train on my own audio and I get an error that seems to be about the slicing of the spectrogram... did you prepare your 44k 16 bit audio in any other way @moiseshorta ? cut it in smaller chunks? Otherwise thanks for a great colab. 

Error in
#Creating Tensorflow Datasets

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-46f65129462c> in <module>()
      6 
      7 dsa = tf.data.Dataset.from_tensor_slices(adata).repeat(50).map(proc, num_parallel_calls=tf.data.experimental.AUTOTUNE).shuffle(10).batch(bs, drop_remainder=True)
----> 8 dsb = tf.data.Dataset.from_tensor_slices(bdata).repeat(50).map(proc, num_parallel_calls=tf.data.experimental.AUTOTUNE).shuffle(10).batch(bs, drop_remainder=True)

17 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    <ipython-input-9-9cbef0b558b1>:5 proc  *
        return tf.image.random_crop(x, size=[hop, 3*shape, 1])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/random_ops.py:382 random_crop
        math_ops.reduce_all(shape >= size),
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py:4003 greater_equal
        "GreaterEqual", x=x, y=y, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py:592 _create_op_internal
        compute_device)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:3536 _create_op_internal
        op_def=op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:2016 __init__
        control_input_ops, op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 0 and 3 for '{{node random_crop/GreaterEqual}} = GreaterEqual[T=DT_INT32](random_crop/Shape, random_crop/size)' with input shapes: [0], [3].`
