### ISSUE TITLE
Issue with pre-processing the dataset

### ISSUE THREAD

**Issue by charvibannur** [marcoppasini/MelGAN-VC#23]
I haven't changed anything, I received an error while running
awv = audio_array('../content/cmu_us_clb_arctic/wav')   
-------------------------------------------------------------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-45-8c9c4e76c626>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 #MALE1
----> 6 awv = audio_array('../content/cmu_us_clb_arctic/wav')                               #get waveform array from folder containing wav files
      7 aspec = tospec(awv)                                                                 #get spectrogram array
      8 adata = splitcut(aspec)                                                             #split spectrogams to fixed length

[<ipython-input-44-cdf4208f7296>](https://localhost:8080/#) in audio_array(path)
      6     x = np.array(x, dtype=np.float32)
      7     adata.append(x)
----> 8   return np.array(adata)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1132,) + inhomogeneous part.

----------------------------------------------------------------------------------------------------------------------------------------------
Any help would be appreciated!

Thanks

**Comment by charvibannur** [comment]
I assume this has got something to do with the length of the audio. I truncated all the files to a fixed length, which solved this problem and ran the rest of the code.

I further run into an issue at this point: 
gen,critic,siam, [opt_gen,opt_disc] = get_networks(shape_new, load_model=False, path='/content/')
The error I get is.
I replaced the name of the variable shape as shape_new to avoid confusion


------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-76-96b14da559ae>](https://localhost:8080/#) in <cell line: 5>()
      3 #If load_model=True, specify the path where the models are saved
      4 
----> 5 gen,critic,siam, [opt_gen,opt_disc] = get_networks(shape_new, load_model=False, path='/content/')

5 frames
[<ipython-input-73-13b8db652e18>](https://localhost:8080/#) in get_networks(shape, load_model, path)
      2 def get_networks(shape, load_model=False, path=None):
      3   if not load_model:
----> 4     gen,critic,siam = build()
      5   else:
      6     gen,critic,siam = load(path)

[<ipython-input-71-b84c72254915>](https://localhost:8080/#) in build()
     11 #Build models
     12 def build():
---> 13   gen = build_generator((hop,shape_new,1))
     14   siam = build_siamese((hop,shape_new,1))
     15   critic = build_critic((hop,3*shape_new,1))                                          #the discriminator accepts as input spectrograms of triple the width of those generated by the generator

[<ipython-input-70-b68fe9309ede>](https://localhost:8080/#) in build_generator(input_shape)
     49   #downscaling
     50   g0 = tf.keras.layers.ZeroPadding2D((0,1))(inp)
---> 51   g1 = conv2d(g0, 256, kernel_size=(h,3), strides=1, padding='valid')
     52   g2 = conv2d(g1, 256, kernel_size=(1,9), strides=(1,2))
     53   g3 = conv2d(g2, 256, kernel_size=(1,7), strides=(1,2))

[<ipython-input-70-b68fe9309ede>](https://localhost:8080/#) in conv2d(layer_input, filters, kernel_size, strides, padding, leaky, bnorm, sn)
      9     Activ = ReLU()
     10   if sn:
---> 11     d = ConvSN2D(filters, kernel_size=kernel_size, strides=strides, padding=padding, kernel_initializer=init, use_bias=False)(layer_input)
     12   else:
     13     d = Conv2D(filters, kernel_size=kernel_size, strides=strides, padding=padding, kernel_initializer=init, use_bias=False)(layer_input)

[/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
    121             # To get the full stack trace, call:
    122             # `keras.config.disable_traceback_filtering()`
--> 123             raise e.with_traceback(filtered_tb) from None
    124         finally:
    125             del filtered_tb

[<ipython-input-69-507a48e7d000>](https://localhost:8080/#) in build(self, input_shape)
     29             channel_axis = -1
     30 
---> 31         self.u = self.add_weight(self.name + '_u',
     32             shape=tuple([1, self.kernel.shape.as_list()[-1]]),
     33             initializer=tf.initializers.RandomNormal(0, 1),

TypeError: Layer.add_weight() got multiple values for argument 'shape'



---------------------------------------------------------------------------------------------------------------------------
Thanks

**Comment by charvibannur** [comment]
Could you share the exact version of tensorflow and keras being used?

**Comment by WinWut** [comment]
Have you fixed it now? I ran into same problem.

**Comment by charvibannur** [comment]
Yes, you need to use Tensorflow=2.12.0

**Comment by charvibannur** [comment]
Yes, you need to use Tensorflow=2.12.0
