### ISSUE TITLE
Recommended amount of audio data for target and source audio

### ISSUE THREAD

**Issue by moih** [marcoppasini/MelGAN-VC#4]
Hi Marco,

Great job on this paper and code, it’s giving me exciting results so far. 

What is the optimal or minimum amount of audio data to have for the source and target datasets in order to achieve the results posted on the paper? 

I have tried an experiment with very few shots of audio on both the target and source audio (around 20 to 12 minutes of speech) and although at some point the model was giving some okay results, the more I trained it, around 2k+ epochs, it was giving me results where the output audio was texturally very similar to the target audio(similar voice tone and cadence) but totally unintelligible as to what the content audio was saying.  I might add that this checkpoint had a D loss of 0.185~ and a G loss of 0.954~.

I’d like to know if there are any special considerations and tips when training not using the ARCTIC dataset.

Thanks.

**Comment by marcoppasini** [comment]
Hi!
Thank you for your interest in this project!
I would recommend at least 1 hour of audio data to train the model and get good results.
Be aware that noisy data makes training much more difficult: you can try to remove background noise with filters before training.
The results you are experiencing are very common when working with very little data. Try changing the weight for the Identity loss term to a higher value and the transfering of content (verbal) information should improve (while the style transfer may deteriorate a bit).

Hope this helps, good luck!
