### ISSUE TITLE
Possible to generate new sounds from latent space

### ISSUE THREAD

**Issue by moih** [marcoppasini/MelGAN-VC#5]
Hi,

I’m curious if the model is able to generate new samples of arbitrary length not by inputting a .wav but by sending a Z vector to the latent space of the generator. And if there’s a simple way to go about this.

Thanks

**Comment by marcoppasini** [comment]
Hi!

I don't think that's possible, as the input of the generator is a spectrogram and not a noise vector as in traditional GANs.
But if you can come up with something, please let me know!
