### ISSUE TITLE
Distorted/clipping outputs in generated audio

### ISSUE THREAD

**Issue by moih** [marcoppasini/MelGAN-VC#6]
Hi Marco,

I've successfully been able to use the code; albeit it gives me distorted audio in some instances when generating a style transfered audio.

I'm wondering how these variables within the hyperparameters are affecting the generation or is it only for the training? These are my hyperparameters when training at 44100Hz samplerate:

```
hop=512              
sr=44100              
min_level_db=-100    
ref_level_db=20
```

Would the adjustments in the `ref_level_db` be able to resolve this?

Many thanks in advance.

**Comment by marcoppasini** [comment]
Hi Moisés,

I would highly recommend you to try first with a sample rate of 16 kHz. If you really need to train at such a high sample rate, keeping the same spectrogram hyperparameters, you must change the value of *shape* to a higher number, as the current value of 24 would include too little time information (around 1/8 of a second, which is way too small of a temporal window).

Don't change the db levels, as their only purpose is to normalize spectrograms.

Hope this helps, and good luck!

**Comment by moih** [comment]
Thanks Marco,

I will try with higher values. What would be the relationship of the _shape_ to the sample rate? 
so if the _shape_ is 24 at 16Khz, would a recommended _shape_ at 44.1Khz be 64?

Thanks!

**Comment by marcoppasini** [comment]
> I will try with higher values. What would be the relationship of the _shape_ to the sample rate?
> so if the _shape_ is 24 at 16Khz, would a recommended _shape_ at 44.1Khz be 64?

Yes, that should hopefully work!
