### ISSUE TITLE
Request for link to pretrained models

### ISSUE THREAD

**Issue by FarisHijazi** [marcoppasini/MelGAN-VC#8]
Thank you for this wonderful project.

It would be very beneficial if you could share the google drive link where you have your pretrained models, it's kind of a waste to need to train the model from scratch every time just to test it.

You could just put the link in the readme or in the notebook.

Thank you.

**Comment by marcoppasini** [comment]
I am working on an updated version of the system with a new architecture. I will try to add a link to some pretrained models as soon as I publish the next version.

Thank you for the interest and for your help!
